//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.03 at 11:21:16 AM ICT 
//


package org.mobilink.employee.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mobilink.employee.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mobilink.employee.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EmployeesDetailModel }
     * 
     */
    public EmployeesDetailModel createEmployeesDetailModel() {
        return new EmployeesDetailModel();
    }

    /**
     * Create an instance of {@link JobPostsModel }
     * 
     */
    public JobPostsModel createJobPostsModel() {
        return new JobPostsModel();
    }

    /**
     * Create an instance of {@link MappingUserModel }
     * 
     */
    public MappingUserModel createMappingUserModel() {
        return new MappingUserModel();
    }

    /**
     * Create an instance of {@link FilesModel }
     * 
     */
    public FilesModel createFilesModel() {
        return new FilesModel();
    }

    /**
     * Create an instance of {@link EmployeesModel }
     * 
     */
    public EmployeesModel createEmployeesModel() {
        return new EmployeesModel();
    }

    /**
     * Create an instance of {@link MainJobPostModel }
     * 
     */
    public MainJobPostModel createMainJobPostModel() {
        return new MainJobPostModel();
    }

    /**
     * Create an instance of {@link JobposResults }
     * 
     */
    public JobposResults createJobposResults() {
        return new JobposResults();
    }

    /**
     * Create an instance of {@link JobposModel }
     * 
     */
    public JobposModel createJobposModel() {
        return new JobposModel();
    }

    /**
     * Create an instance of {@link JobposShortModel }
     * 
     */
    public JobposShortModel createJobposShortModel() {
        return new JobposShortModel();
    }

    /**
     * Create an instance of {@link FilesResults }
     * 
     */
    public FilesResults createFilesResults() {
        return new FilesResults();
    }

    /**
     * Create an instance of {@link EmployeesShortModel }
     * 
     */
    public EmployeesShortModel createEmployeesShortModel() {
        return new EmployeesShortModel();
    }

    /**
     * Create an instance of {@link EmployeesInputModel }
     * 
     */
    public EmployeesInputModel createEmployeesInputModel() {
        return new EmployeesInputModel();
    }

    /**
     * Create an instance of {@link EmployeesResults }
     * 
     */
    public EmployeesResults createEmployeesResults() {
        return new EmployeesResults();
    }

}
